package ac.ruraluniv.gri.navigation

sealed class Screen(val route: String) {
    object Splash : Screen("splash")
    object Login : Screen("login")
    object Register : Screen("register")
    object Home : Screen("home")
    object Menu : Screen("menu")
    object About : Screen("about")
    object Governance : Screen("governance")
    object Schools : Screen("schools")
    object Departments : Screen("departments")
    object Admissions : Screen("admissions")
    object Facilities : Screen("facilities")
    object ENews : Screen("enews")
    object Videos : Screen("videos")
    object Downloads : Screen("downloads")
    object Portal : Screen("portal")
    object Contacts : Screen("contacts")
    object StudentProfile : Screen("profile")
    object Attendance : Screen("attendance")
    object Results : Screen("results")
    object Examinations : Screen("examinations")
    object Settings : Screen("settings")
}
